package com.mpatric.mp3agic;

public class ID3v1Genres {
	public static final String[] GENRES = {
			"Blues",
			"Classic Rock",
			"Country",
			"Dance",
			"Disco",
			"Funk",
			"Grunge",
			"Hip-Hop",
      "Hip-Hop/Rap",
			"Jazz",
			"Metal",
			"New Age",
			"Oldies",
			"Other",
			"Pop",
			"R&B",
			"Rap",
			"Reggae",
			"Rock",
			"Techno",
			"Industrial",
			"Alternative",
			"Ska",
			"Death Metal",
			"Downtempo",
			"Soundtrack",
			"Euro-Techno",
			"Ambient",
			"City Pop",
			"Vocal",
			"Jazz+Funk",
			"Fusion",
			"Trance",
			"Classical",
			"Instrumental",
			"Acid",
			"House",
			"Game",
			"Sound Clip",
			"Gospel",
			"Noise",
			"Alt Rock",
			"Bass",
			"Soul",
			"Punk",
			"Space",
			"Meditative",
			"Instrumental Pop",
			"Instrumental Rock",
			"Dubstep",
			"Gothic",
			"Darkwave",
			"Techno-Industrial",
			"Electronic",
			"Pop-Folk",
			"Eurodance",
			"Nerdcore",
			"Southern Rock",
			"Comedy",
			"Cult",
			"Gangsta",
			"Top 40",
			"Christian Rap",
			"Pop/Funk",
      "Pop/Rock",
			"Jungle",
			"Native American",
			"Cabaret",
			"New Wave",
			"Psychedelic",
			"Rave",
			"Showtunes",
			"Americana",
			"Lo-Fi",
			"Tribal",
			"Acid Punk",
			"Acid Jazz",
			"Polka",
			"Retro",
			"Musical",
      "Musicals",
			"Rock & Roll",
			"Hard Rock",
			"Folk",
			"Folk/Rock",
			"National Folk",
			"Swing",
			"Fast Fusion",
			"Bebob",
			"Latin",
			"Revival",
			"Celtic",
			"Bluegrass",
			"Avantgarde",
			"Gothic Rock",
			"Progressive Rock",
			"Psychedelic Rock",
			"Symphonic Rock",
			"Slow Rock",
			"Big Band",
			"Chorus",
			"Easy Listening",
			"Acoustic",
			"Humour",
			"Speech",
			"Chanson",
			"Opera",
			"Chamber Music",
			"Sonata",
			"Symphony",
			"Booty Bass",
			"Primus",
			"Vocaloid",
			"Satire/Parody",
			"Slow Jam",
			"Club",
			"Tango",
			"Samba",
			"Folklore",
			"Ballad",
			"Power Ballad",
			"Rhythmic Soul",
			"Freestyle",
			"Duet",
			"Punk Rock",
			"Drum Solo",
			"Acapella",
			"Euro-House",
			"Dance Hall",
			"Goa",
			"Drum & Bass",
			"Club-House",
			"Hardcore",
			"Terror",
			"Indie",
			"BritPop",
			"Negerpunk",
			"Polsk Punk",
			"Beat",
			"Christian Gangsta",
			"Heavy Metal",
			"Black Metal",
			"Crossover",
			"Contemporary Chr",
			"Christian Rock",
			"Merengue",
			"Salsa",
			"Thrash Metal",
			"Anime",
			"J-Pop",
			"Synthpop",
      "Electro Swing",
      "Electronica",
      "Enka",
      "French Pop",
      "Holiday",
      "Indie Pop",
      "Indie Rock",
      "Indonesian Pop",
      "J-Rock",
      "K-Pop",
      "Singer/Songwriter",
      "Video Game",
      "V-Pop",
	};

	/**
	 * Match provided description against genres, ignoring case.
	 *
	 * @param description genre description
	 * @return matching genre index or -1
	 */
	public static int matchGenreDescription(String description) {
		if (description != null && !description.isEmpty()) {
			for (int i = 0; i < ID3v1Genres.GENRES.length; i++) {
				if (ID3v1Genres.GENRES[i].equalsIgnoreCase(description)) {
					return i;
				}
			}
		}
		return -1;
	}
}
